<?php
/**
 * Plugin Name: Audio Level Matcher
 * Description: Automatically normalizes loudness across all audio players on a page using Web Audio API. Works with WordPress [audio] shortcodes and any <audio> element.
 * Version:     1.0.0
 * Author:      Your Name
 * License:     GPL-2.0-or-later
 * Requires PHP: 7.4
 * Requires at least: 5.8
 *
 * HOW IT WORKS
 * ─────────────
 * 1. Adds crossorigin="anonymous" to all <audio> elements generated by WordPress
 *    (required for Web Audio API to process audio from the same origin).
 * 2. Enqueues a small JavaScript file that:
 *    - Auto-discovers every <audio> element on the page.
 *    - On first play, fetches the audio file, measures its RMS loudness offline,
 *      and computes a gain correction to match all tracks to a configurable target.
 *    - Applies the gain through a Web Audio GainNode — non-destructive, real-time.
 *    - Degrades gracefully: if anything fails, the audio plays at its original level.
 */

defined( 'ABSPATH' ) || exit;

/* ──────────────────────────────────────────────────────────────────
 * Constants
 * ────────────────────────────────────────────────────────────────── */

define( 'ALM_VERSION', '1.0.0' );
define( 'ALM_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
define( 'ALM_PLUGIN_URL', plugin_dir_url( __FILE__ ) );

/* ──────────────────────────────────────────────────────────────────
 * 1. SETTINGS — Register options + admin page
 * ────────────────────────────────────────────────────────────────── */

/**
 * Return plugin defaults in one place.
 * Every option lives in a single DB row: 'alm_options'.
 */
function alm_defaults(): array {
	return [
		'target_loudness'    => -18,   // dBFS RMS target. Common values: -14 (streaming), -18 (web), -23 (broadcast).
		'max_gain'           => 12,    // Maximum boost in dB.
		'min_gain'           => -12,   // Maximum cut in dB (stored as negative).
		'analysis_duration'  => 10,    // Seconds of audio to analyze (from the start of the file).
		'gain_ramp_time'     => 0.05,  // Seconds for the gain change to ramp (avoids clicks).
		'mutual_exclusion'   => true,  // Pause other players when one starts.
		'enabled'            => true,  // Master on/off switch.
	];
}

/**
 * Get current options, merged with defaults so new options
 * added in future versions always have a value.
 */
function alm_get_options(): array {
	return wp_parse_args( get_option( 'alm_options', [] ), alm_defaults() );
}

/**
 * Register settings, sections, and fields.
 * Uses the WordPress Settings API — no custom form handling needed.
 */
add_action( 'admin_init', function () {

	register_setting( 'alm_settings_group', 'alm_options', [
		'type'              => 'array',
		'sanitize_callback' => 'alm_sanitize_options',
		'default'           => alm_defaults(),
	] );

	/* ── Section: Loudness ── */
	add_settings_section(
		'alm_section_loudness',
		'Loudness',
		function () {
			echo '<p>Controls how audio levels are matched. The target loudness is the level all audio will be normalized to. '
			   . 'Gain limits prevent extreme corrections on very quiet or very loud files.</p>';
		},
		'alm-settings'
	);

	add_settings_field( 'target_loudness', 'Target loudness (dBFS RMS)', 'alm_field_target_loudness', 'alm-settings', 'alm_section_loudness' );
	add_settings_field( 'max_gain',        'Max boost (dB)',             'alm_field_max_gain',        'alm-settings', 'alm_section_loudness' );
	add_settings_field( 'min_gain',        'Max cut (dB)',               'alm_field_min_gain',        'alm-settings', 'alm_section_loudness' );
	add_settings_field( 'analysis_duration', 'Analysis duration (seconds)', 'alm_field_analysis_duration', 'alm-settings', 'alm_section_loudness' );

	/* ── Section: Behavior ── */
	add_settings_section(
		'alm_section_behavior',
		'Behavior',
		function () {
			echo '<p>General playback behavior settings.</p>';
		},
		'alm-settings'
	);

	add_settings_field( 'mutual_exclusion', 'One player at a time', 'alm_field_mutual_exclusion', 'alm-settings', 'alm_section_behavior' );
	add_settings_field( 'enabled',          'Enable level matching', 'alm_field_enabled',          'alm-settings', 'alm_section_behavior' );
} );

/* ── Field renderers ── */

function alm_field_target_loudness() {
	$opts = alm_get_options();
	$val  = (float) $opts['target_loudness'];

	// Dropdown with the most common standard targets.
	$presets = [
		-14 => '-14 dBFS (loud — streaming platforms)',
		-16 => '-16 dBFS (moderately loud)',
		-18 => '-18 dBFS (default — good general balance)',
		-20 => '-20 dBFS (moderate)',
		-23 => '-23 dBFS (quiet — EBU broadcast standard)',
	];
	echo '<select name="alm_options[target_loudness]" id="alm_target_loudness">';
	foreach ( $presets as $db => $label ) {
		printf(
			'<option value="%s" %s>%s</option>',
			esc_attr( $db ),
			selected( $val, $db, false ),
			esc_html( $label )
		);
	}
	echo '</select>';
	echo '<p class="description">The RMS level all audio will be normalized to. '
	   . 'Lower values = quieter. -18 dBFS is a safe default for most web use.</p>';
}

function alm_field_max_gain() {
	$opts = alm_get_options();
	printf(
		'<input type="number" name="alm_options[max_gain]" value="%s" min="0" max="24" step="1" class="small-text" /> dB',
		esc_attr( $opts['max_gain'] )
	);
	echo '<p class="description">Maximum boost applied to quiet tracks. 12 dB is safe; higher risks amplifying noise.</p>';
}

function alm_field_min_gain() {
	$opts = alm_get_options();
	// Stored as negative (e.g., -12), but display the absolute value for clarity.
	$abs = abs( (float) $opts['min_gain'] );
	printf(
		'<input type="number" name="alm_options[min_gain]" value="%s" min="0" max="24" step="1" class="small-text" /> dB',
		esc_attr( $abs )
	);
	echo '<p class="description">Maximum cut applied to loud tracks (entered as a positive number, applied as negative).</p>';
}

function alm_field_analysis_duration() {
	$opts = alm_get_options();
	printf(
		'<input type="number" name="alm_options[analysis_duration]" value="%s" min="1" max="60" step="1" class="small-text" /> seconds',
		esc_attr( $opts['analysis_duration'] )
	);
	echo '<p class="description">How many seconds from the start of each file to analyze. '
	   . 'Longer = more accurate but slower on first play. 10 seconds works well for most content.</p>';
}

function alm_field_mutual_exclusion() {
	$opts = alm_get_options();
	printf(
		'<label><input type="checkbox" name="alm_options[mutual_exclusion]" value="1" %s /> '
		. 'Pause other audio players when one starts playing</label>',
		checked( $opts['mutual_exclusion'], true, false )
	);
}

function alm_field_enabled() {
	$opts = alm_get_options();
	printf(
		'<label><input type="checkbox" name="alm_options[enabled]" value="1" %s /> '
		. 'Enable audio level matching on the front end</label>',
		checked( $opts['enabled'], true, false )
	);
	echo '<p class="description">Uncheck to disable the plugin without deactivating it. Audio will play at its original level.</p>';
}

/**
 * Sanitize and validate all options before saving.
 * Returns a clean array safe to store in the database.
 */
function alm_sanitize_options( $input ): array {
	$defaults  = alm_defaults();
	$sanitized = [];

	// Target loudness: must be one of the preset values.
	$allowed_targets = [ -14, -16, -18, -20, -23 ];
	$target = isset( $input['target_loudness'] ) ? (int) $input['target_loudness'] : $defaults['target_loudness'];
	$sanitized['target_loudness'] = in_array( $target, $allowed_targets, true ) ? $target : $defaults['target_loudness'];

	// Gain limits: integers within reasonable bounds.
	$sanitized['max_gain'] = isset( $input['max_gain'] )
		? clamp_int( (int) $input['max_gain'], 0, 24 )
		: $defaults['max_gain'];

	// min_gain is entered as positive, stored as negative.
	$sanitized['min_gain'] = isset( $input['min_gain'] )
		? -1 * abs( clamp_int( (int) $input['min_gain'], 0, 24 ) )
		: $defaults['min_gain'];

	// Analysis duration: 1–60 seconds.
	$sanitized['analysis_duration'] = isset( $input['analysis_duration'] )
		? clamp_int( (int) $input['analysis_duration'], 1, 60 )
		: $defaults['analysis_duration'];

	// Gain ramp time: not exposed in UI, keep default.
	$sanitized['gain_ramp_time'] = $defaults['gain_ramp_time'];

	// Checkboxes: absent = unchecked = false.
	$sanitized['mutual_exclusion'] = ! empty( $input['mutual_exclusion'] );
	$sanitized['enabled']          = ! empty( $input['enabled'] );

	return $sanitized;
}

/**
 * Tiny helper — PHP doesn't have a built-in integer clamp until 8.x.
 */
function clamp_int( int $val, int $min, int $max ): int {
	return max( $min, min( $max, $val ) );
}

/* ──────────────────────────────────────────────────────────────────
 * 2. ADMIN PAGE — Simple, single-page settings screen
 * ────────────────────────────────────────────────────────────────── */

add_action( 'admin_menu', function () {
	add_options_page(
		'Audio Level Matcher',       // Page title.
		'Audio Level Matcher',       // Menu title.
		'manage_options',            // Capability.
		'alm-settings',              // Menu slug.
		'alm_render_settings_page'   // Callback.
	);
} );

/**
 * Render the settings page using the Settings API.
 */
function alm_render_settings_page() {
	if ( ! current_user_can( 'manage_options' ) ) {
		return;
	}
	?>
	<div class="wrap">
		<h1><?php echo esc_html( get_admin_page_title() ); ?></h1>

		<p>
			Audio Level Matcher automatically normalizes the loudness of all
			<code>&lt;audio&gt;</code> players on your pages so they play at a
			consistent volume — no matter how loud or quiet the uploaded files are.
		</p>

		<form action="options.php" method="post">
			<?php
			settings_fields( 'alm_settings_group' );
			do_settings_sections( 'alm-settings' );
			submit_button();
			?>
		</form>
	</div>
	<?php
}

/* ──────────────────────────────────────────────────────────────────
 * 3. FRONTEND — Inject crossorigin attribute + enqueue JS
 * ────────────────────────────────────────────────────────────────── */

/**
 * Add crossorigin="anonymous" to WordPress audio shortcode output.
 *
 * Without this, the Web Audio API cannot access audio data from
 * <audio> elements (CORS security restriction). The audio must also
 * be served from the same origin or with appropriate CORS headers.
 */
add_filter( 'wp_audio_shortcode', function ( string $html ): string {
	// Only modify if not already present.
	if ( str_contains( $html, 'crossorigin' ) ) {
		return $html;
	}
	return str_replace( '<audio', '<audio crossorigin="anonymous"', $html );
}, 10, 1 );

/**
 * Enqueue the level-matching script on the front end.
 *
 * - Only loads when the plugin is enabled.
 * - Passes PHP-configured options to JS via wp_localize_script.
 * - Loaded in the footer so it runs after audio elements exist in the DOM.
 */
add_action( 'wp_enqueue_scripts', function () {
	$opts = alm_get_options();

	// Bail if disabled — audio plays normally without the script.
	if ( empty( $opts['enabled'] ) ) {
		return;
	}

	wp_enqueue_script(
		'audio-level-matcher',
		ALM_PLUGIN_URL . 'js/audio-level-matcher.js',
		[],            // No dependencies.
		ALM_VERSION,
		true           // Load in footer.
	);

	// Pass config from PHP → JS as a global object.
	wp_localize_script( 'audio-level-matcher', 'almConfig', [
		'targetRmsDbfs'    => (float) $opts['target_loudness'],
		'maxGainDb'        => (float) $opts['max_gain'],
		'minGainDb'        => (float) $opts['min_gain'],
		'analysisDuration' => (int)   $opts['analysis_duration'],
		'gainRampTime'     => (float) $opts['gain_ramp_time'],
		'mutualExclusion'  => (bool)  $opts['mutual_exclusion'],
	] );
} );
